// Barrel for the full Drizzle schema. `auth.ts` is generated by the Better Auth CLI
// (do not hand-edit); `membrane.ts` is the hand-written record layer (ADR-0002).
export * from "./auth";
export * from "./membrane";
export * from "./trust";
